# Memoria máxima para Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Permite reutilizar resultados de compilaciones anteriores
org.gradle.caching=true

# Mantiene activo el proceso de Gradle para acelerar compilaciones posteriores
org.gradle.daemon=true

# Compilación incremental de Kotlin
kotlin.incremental=true

# Estilo oficial de Kotlin
kotlin.code.style=official